mysite/dnd/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("regiony/", views.Region.as_view(), name="regiony"),
    path("staty/", views.Stat.as_view(), name="staty"),
    path("mesta/", views.Mesto.as_view(), name="mesta"),
    path("npcs/", views.NPCs.as_view(), name="npcs"),
    path("npcs/npc/<int:pk>", views.Npc.as_view(), name="npcDetail"),
    path("npcs/npc/<int:pk>/printable", views.NpcPrint.as_view(), name="npcPrint"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("dnd.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/dnd/models.py
from django.db import models


from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core import validators

def uploadnuto(instance, filename):
    return '{0}/{1}/{2}/{3}'.format(instance.region.nazev, instance.nazev, instance.changed_filename, filename)

def upload_mapa(instance, filename):
    return '{0}/{1}/{2}'.format(instance.nazev, instance.changed_filename, filename)
def upload_vladce(instance, filename):
    lowercase_text = instance.jmeno.lower()
    converted_text = lowercase_text.replace(' ', '_')
    return '{0}/{1}/{2}/{3}.jpg'.format(instance.stat_nazev.region.nazev, instance.stat_nazev.nazev, instance.changed_filename, converted_text)


def upload_mesto(instance, filename):
    if instance.hlavni == "ne":
        return '{0}/{1}/{2}/{3}.jpg'.format(instance.stat_nazev.region.nazev, instance.stat_nazev.nazev, instance.changed_filename, instance.nazev)
    else:
        return '{0}/{1}/capital/{2}.jpg'.format(instance.stat_nazev.region.nazev, instance.stat_nazev.nazev, instance.nazev)


def get_npc_upload_path(instance, filename):
    mesto_names = "_".join([mesto.stat_nazev.region.nazev + "/" + mesto.stat_nazev.nazev for mesto in instance.mesto.all()])
    return f"{mesto_names}/places/{instance.vztahHraci}/{instance.jmeno}_{instance.prijmeni}.jpg"

def get_place_upload_path(instance, filename):
    mesto_names = "_".join([mesto.stat_nazev.region.nazev + "/" + mesto.stat_nazev.nazev for mesto in instance.mesto.all()])
    return f"{mesto_names}/places/{instance.typ}/{instance.nazev}.png"

def get_budova_upload_path(instance, filename):
    mesto_names = "_".join([mesto.stat_nazev.region.nazev + "/" + mesto.stat_nazev.nazev for mesto in instance.mesto.all()])
    return f"{mesto_names}/budovy/{instance.typ_budovy}/{instance.nazev}.png"


class Opevneni(models.Model):
    typ = models.CharField(max_length=45, primary_key=True, verbose_name='Typ opevnění')

    class Meta:
        ordering = ["typ"]
        verbose_name = 'Opevnění'
        verbose_name_plural = 'Opevnění'

    def __str__(self):
        return self.typ


class Povaha(models.Model):
    povaha = models.CharField(max_length=45, primary_key=True, verbose_name="Typ povahy")

    class Meta:
        ordering = ["povaha"]
        verbose_name = 'Povaha'
        verbose_name_plural = 'Povahy'

    def __str__(self):
        return self.povaha

class Geografie(models.Model):
    CHOICES_TYP = (
        ('hora', 'Hora'),
        ('pohori', 'Pohoří'),
        ('hvozd', 'Hvozd'),
        ('les', 'Les'),
        ('poust', 'Poušť'),
        ('kopce', 'Kopce')
    )

    nazev = models.CharField(max_length=50, primary_key=True, verbose_name='Název místa')
    typ = models.CharField(max_length=10, choices=CHOICES_TYP, verbose_name='Typ místa')
    zajimavost = models.TextField(blank=True, verbose_name='Zajímavosti', help_text="Nejvyšší hora, historie místa etc.")

    class Meta:
        ordering = ['nazev']
        verbose_name = 'Geografie'
        verbose_name_plural = 'Geografie'

    def __str__(self):
        return self.nazev

class Region(models.Model):
    nazev = models.CharField(max_length=50, primary_key=True, verbose_name='Jméno regionu')
    podnebi = models.CharField(max_length=50, choices=[
        ('tropicke', 'tropicke'),
        ('subtropicke', 'subtropicke'),
        ('mírné', 'mírné'),
        ('subpolární', 'subpolární'),
        ('polární', 'polární'),
    ], verbose_name='Podnebí')

    popis = models.TextField(blank=True, verbose_name='Popis', help_text="Popište základní geografické části regionu, jeho historii a státy které se zde nachází")
    changed_filename = models.CharField(max_length=50, default="mapa", editable=False)
    geografie = models.ManyToManyField(Geografie)
    mapa = models.ImageField(upload_to=upload_mapa, blank=True, verbose_name="Mapa")
    class Meta:
        ordering = ["nazev"]
        verbose_name = 'Region'
        verbose_name_plural = 'Regiony'

    def __str__(self):
        return f"{self.nazev} ({self.podnebi})"


class PolitickeUsporadani(models.Model):
    nazev = models.CharField(max_length=45, primary_key=True, verbose_name="Název")
    popis = models.CharField(max_length=45, blank=True, verbose_name="Popis", help_text="Popis jak daný systém funguje")

    class Meta:
        ordering = ["nazev"]
        verbose_name = 'Politické uspořádání'
        verbose_name_plural = 'Politická uspořádání'

    def __str__(self):
        return self.nazev


class Stat(models.Model):
    nazev = models.CharField(max_length=50, primary_key=True)
    rozloha = models.CharField(max_length=50, choices=[
        ('obrovská', 'obrovská'),
        ('velka', 'velka'),
        ('stredni', 'stredni'),
        ('mala', 'mala'),
    ])
    #potom forgien key
    politicke_usporadani = models.ManyToManyField(PolitickeUsporadani, verbose_name="Politické uspořádání")
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    changed_filename = models.CharField(max_length=50,default="vlajka", editable=False)
    vlajka = models.ImageField(upload_to=uploadnuto, blank=True, verbose_name="Vlajka")

    class Meta:
        ordering = ["nazev"]
        verbose_name = 'Stát'
        verbose_name_plural = 'Státy'

    def __str__(self):
        return self.nazev


class TypMesta(models.Model):
    typ = models.CharField(max_length=50, primary_key=True, verbose_name="Typ města" ,help_text="Přístav, vesnice, město etc.")

    class Meta:
        ordering = ["typ"]
        verbose_name = 'Typ města'
        verbose_name_plural = 'Typy města'

    def __str__(self):
        return f"{self.typ}"


class Mesto(models.Model):
    nazev = models.CharField(max_length=50, primary_key=True, verbose_name="Název města")
    pocet_obyvatel = models.IntegerField(verbose_name="Počet obyvatel města")
    changed_filename = models.CharField(max_length=50, default="mesto_vesnice", editable=False)
    mapa = models.ImageField(upload_to=upload_mesto, blank=True)
    hlavni = models.CharField(max_length=20, choices=[
        ('ano','Ano'),
        ('ne','Ne'),
    ], verbose_name="Jedná se o hlavní město?")
    stat_nazev = models.ForeignKey(Stat, on_delete=models.CASCADE, verbose_name="Stát")
    typ_mesta = models.ForeignKey(TypMesta, on_delete=models.CASCADE, verbose_name="Typ města")

    opevneni_typ = models.ManyToManyField(Opevneni,verbose_name="Typ opevnění")

    class Meta:
        ordering = ["nazev"]
        verbose_name = 'Město'
        verbose_name_plural = 'Města'

    def __str__(self):
        if self.hlavni=='ne':
            return f"{self.stat_nazev} {self.typ_mesta}: {self.nazev}"
        else:
            return f"{self.stat_nazev} Hlavní město je {self.typ_mesta}: {self.nazev})"


class InterestingPlaces(models.Model):
    nazev = models.CharField(max_length=50, verbose_name="Název místa")
    popis = models.CharField(max_length=45, blank=True, verbose_name="Popis", help_text="Popis místa")
    typ = models.CharField(max_length=20, choices=[
        ('dungeon','Dungeon'),
        ('jeskyně','Jeskyně'),
        ('place_of_power', "Místo moci"),
        ('building', 'Budova'),
    ], verbose_name="Typ místa")
    mapa = models.ImageField(upload_to=get_place_upload_path, verbose_name="Mapa", blank=True)
    mesto = models.ForeignKey(Mesto, on_delete=models.CASCADE, verbose_name="Město")

    class Meta:
        ordering = ["nazev"]
        verbose_name = 'Zajímavé místo'
        verbose_name_plural = 'Zajímavá místa'

    def __str__(self):
            return f"{ self.typ} {self.nazev}"
class NPC(models.Model):
    idnpc = models.IntegerField(primary_key=True)
    jmeno = models.CharField(max_length=45, null=True)
    prijmeni = models.CharField(max_length=45)
    rasa = models.CharField(max_length=45, choices=[
        ('elf', 'Elf'),
        ('trpaslík', 'Trpaslík'),
        ('člověk', 'Člověk'),
        ('gnóm', 'Gnóm'),
        ('půlork', 'Půl-ork'),
        ('drakorozený', 'Drakorozený'),
        ('půlčík', 'Půlčík'),
        ('půlelf', 'Půl-elf'),
        ('tiefling', 'Tiefling'),
        ('jine', 'Jiné'),
    ])
    vek = models.IntegerField(default=20, verbose_name="Věk")
    vyska = models.IntegerField(blank=True, verbose_name="Výška")
    oci = models.CharField(max_length=45, blank=True, verbose_name="Oči")
    oblicej = models.CharField(max_length=45, blank=True, verbose_name="Obličej")
    kladne_vlastnosti = models.CharField(max_length=150, blank=True, verbose_name="Kladné vlastnosti")
    zaporne_vlastnosti = models.CharField(max_length=150, blank=True, verbose_name="Záporné vlastnosti")
    specifickeZnaky = models.CharField(max_length=45, blank=True, verbose_name="Specifické znaky",
                                          help_text="Tetování etc.")
    #změnit (enum)
    vztahHraci = models.CharField(max_length=150, blank=True,  verbose_name="Vztah k hráčům", choices=[
        ('friendly','Přátelský'),
        ('neutrall', 'Neutrální'),
        ('hostile', 'Nepřátelský'),
    ])

    stat_nazev = models.ForeignKey(Stat, on_delete=models.CASCADE, verbose_name="Stát")
    povaha = models.ForeignKey(Povaha, on_delete=models.CASCADE, verbose_name="Povaha")
    fotka = models.ImageField(upload_to=get_npc_upload_path, verbose_name="Fotka", blank=True)
    mesto = models.ManyToManyField(Mesto)

    class Meta:
        ordering = ["prijmeni"]
        verbose_name = 'NPC'
        verbose_name_plural = 'NPCs'

    def __str__(self):
        return f"NPC: {self.jmeno} {self.prijmeni} ({self.rasa} : {self.povaha})"


class Spravce(models.Model):
    spravce = models.ForeignKey(NPC, on_delete=models.CASCADE, verbose_name="Správce města")
    mesto = models.ForeignKey(Mesto, on_delete=models.CASCADE, verbose_name="Město")

    class Meta:
        ordering = ["spravce"]
        verbose_name = 'Správce města'
        verbose_name_plural = 'Správci měst'

    def __str__(self):
        return f"{self.mesto.nazev} {self.spravce.prijmeni}"

mysite/dnd/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View
from .models import *

def index(request):
    return render(request, "index.html", context=None)

class Region(ListView):
    model = Region
    ordering = ["nazev"]
    context_object_name = "regiony"
    template_name = "region/region.html"

class Stat(ListView):
    model = Stat
    ordering = ["region"]
    context_object_name = "staty"
    template_name = "stat/stat.html"

class Mesto(ListView):
    model = Mesto
    ordering = ["stat_nazev"]
    context_object_name = "mesta"
    template_name = "mesta/mesta.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['spravci'] = Spravce.objects.select_related('spravce', 'mesto')
        return context

class NPCs(ListView):
    model = NPC
    ordering = ["prijmeni"]
    context_object_name = "NPCs"
    template_name = "NPC/npcs.html"

class Npc(DetailView):
    model = NPC
    context_object_name = "NPC"
    template_name = "NPC/npcDetail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        npc = self.get_object()
        context['spravci'] = Spravce.objects.filter(spravce=npc)
        context['vladce'] = VladceStatu.objects.filter(vladce=npc)
        context['stattable'] = StatTable.objects.filter(npc=npc)
        context['actions'] = Actions.objects.filter(npc=npc)
        return context

class NpcPrint(DetailView):
    model = NPC
    context_object_name = "NPC"
    template_name = "NPC/printable.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        npc = self.get_object()
        context['spravci'] = Spravce.objects.filter(spravce=npc)
        context['vladce'] = VladceStatu.objects.filter(vladce=npc)
        context['stattable'] = StatTable.objects.filter(npc=npc)
        context['actions'] = Actions.objects.filter(npc=npc)
        return context

    # model = MyModel
    #
    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     # Apply filtering logic
    #     filtered_queryset = queryset.filter(my_field='my_value')
    #     return filtered_queryset

mysite/dnd/templates/NPC/npcDetail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h1>NPC Detail</h1>
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th>Jméno</th>
                            <td>{{ NPC.jmeno }}</td>
                        </tr>
                        <tr>
                            <th>Příjmení</th>
                            <td>{{ NPC.prijmeni }}</td>
                        </tr>
                        <tr>
                            <th>Rasa</th>
                            <td>{{ NPC.get_rasa_display }}</td>
                        </tr>
                        <tr>
                            <th>Věk</th>
                            <td>{{ NPC.vek }}</td>
                        </tr>
                        <tr>
                            <th>Výška</th>
                            <td>{{ NPC.vyska }}</td>
                        </tr>
                        <tr>
                            <th>Oči</th>
                            <td>{{ NPC.oci }}</td>
                        </tr>
                        <tr>
                            <th>Obličej</th>
                            <td>{{ NPC.oblicej }}</td>
                        </tr>
                        <tr>
                            <th>Kladné vlastnosti</th>
                            <td>{{ NPC.kladne_vlastnosti }}</td>
                        </tr>
                        <tr>
                            <th>Záporné vlastnosti</th>
                            <td>{{ NPC.zaporne_vlastnosti }}</td>
                        </tr>
                        <tr>
                            <th>Specifické znaky</th>
                            <td>{{ NPC.specifickeZnaky }}</td>
                        </tr>
                        <tr>
                            <th>Vztah k hráčům</th>
                            <td>{{ NPC.get_vztahHraci_display }}</td>
                        </tr>
                        <tr>
                            <th>Stát</th>
                            <td>{{ NPC.stat_nazev }}</td>
                        </tr>
                        <tr>
                            <th>Povaha</th>
                            <td>{{ NPC.povaha }}</td>
                        </tr>
                        {% if NPC.fotka %}
                        <tr>
                            <th>Fotka</th>
                            <td><img src="{{ NPC.fotka.url }}" alt="Fotka" width="100%"></td>
                        </tr>
                        {% endif %}
                        <tr>
                            <th>Nachází se</th>
                            <td>
                                <ul>
                                    {% for m in NPC.mesto.all %}
                                        <li>{{ m.nazev }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        {% for s in spravci %}
                            {% if s.spravce_id == NPC.idnpc %}
                            <tr>
                                <th>Správce města</th>
                                <td>
                                    {{ s.mesto.nazev }} ({{ s.mesto.stat_nazev.nazev }})
                                </td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                        {% for v in vladce %}
                            {% if v.vladce_id == NPC.idnpc %}
                            <tr>
                                <th>Vládce státu</th>
                                <td>
                                    <b>{{ v.stat.nazev }} ({{ v.stat.politicke_usporadani }})</b>
                                </td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-8">
                <h2>StatTable</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Síla</th>
                            <th>Obratnost</th>
                            <th>Výdrž</th>
                            <th>Inteligence</th>
                            <th>Moudrost</th>
                            <th>Charisma</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for stattable in stattable %}
                            <tr>
                                <td>{{ stattable.sila }}&nbsp;[{{ stattable.sila_modifier }}]</td>
                                <td>{{ stattable.obratnost }}&nbsp;[{{ stattable.obratnost_modifier}}]</td>
                                <td>{{ stattable.vydrz }}&nbsp;[{{ stattable.vydrz_modifier }}]</td>
                                <td>{{ stattable.inteligence }}&nbsp;[{{ stattable.inteligence_modifier }}]</td>
                                <td>{{ stattable.moudrost }}&nbsp;[{{ stattable.moudrost_modifier }}]</td>
                                <td>{{ stattable.charisma }}&nbsp;[{{ stattable.charisma_modifier }}]</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="6">No StatTable available.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <h2>Basic stats table</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Brnění</th>
                            <th>Životy</th>
                            <th>Kostky životů</th>
                            <th>Rychlost</th>
                            <th>Vnímání</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for stattable in stattable %}
                            <tr>
                                <td>{{ stattable.ac }}</td>
                                <td>{{ stattable.health_die }}</td>
                                <td>{{ stattable.roll_health }}</td>
                                <td>{{ stattable.speed }} sáhů</td>
                                <td>{{ stattable.perception }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="6">No StatTable available.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <h2>Actions</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Název</th>
                            <th>Maximální poškození</th>
                            <th>Bonus k zásahu</th>
                            <th>Dosah</th>
                            <th>Dosah na dálku</th>
                            <th>DC</th>
                            <th>Popis</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for action in actions %}
                            <tr>
                                <td>{{ action.nazev }}</td>
                                <td>{{ action.max_dmg }}</td>
                                <td>{{ action.bonus_to_hit }}</td>
                                <td>{{ action.reach }}</td>
                                <td>{{ action.range }}</td>
                                <td>{{ action.dc }}</td>
                                <td>{{ action.desc }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="8">No Actions available.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <p><a class="btn btn-success w-100" target="_blank" href="{% url 'npcPrint' NPC.idnpc %}">Tisknutelná verze</a></p>
            </div>
        </div>
    </div>
{% endblock %}

mysite/dnd/templates/NPC/npcs.html
{% extends 'base.html' %}


{% block content %}
    <div class="container pt-5">
        <div class="row">
        {% for npc in NPCs %}
            <div class="col-md-4">
                <div class="card bg-light mb-3" style="max-width: 18rem; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
                    {% if npc.fotka %}
                        <img src="{{ npc.fotka.url }}" class="card-img-top" alt="{{ npc.prijmeni }}">
                    {% endif %}
                  <div class="card-header"><a href="{% url 'npcDetail' npc.idnpc %}">{{ npc.jmeno }} {{ npc.prijmeni }}</a></div>
                  <div class="card-body">
                    <h5 class="card-title">{{ npc.rasa }}, {{ npc.povaha }}</h5>
                    <p class="card-text">Věk: {{ npc.vek }} let</p>
                    <p class="card-text">Výška: {{ npc.vyska }} cm</p>
                    <p class="card-text">Výskyt ve <b>{% for m in npc.mesto.all %}{{ m.nazev }} {% endfor %}</b></p>
                    <p class="card-text">Vztah k hráčům <b>{{ npc.vztahHraci }}</b></p>
                    <p class="card-text"></p>
                  </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

mysite/dnd/templates/NPC/printable.html
<style>
    .npc-table {
        border-collapse: collapse;
        width: 100%;
    }

    .npc-table th,
    .npc-table td {
        border: 1px solid #ddd;
        padding: 8px;
    }

    .npc-table th {
        background-color: #f2f2f2;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <h1>NPC Detail</h1>
            <table class="npc-table">
                <tbody>
                    <tr>
                        <th>Jméno</th>
                        <td>{{ NPC.jmeno }}</td>
                    </tr>
                    <tr>
                        <th>Příjmení</th>
                        <td>{{ NPC.prijmeni }}</td>
                    </tr>
                    <tr>
                        <th>Rasa</th>
                        <td>{{ NPC.get_rasa_display }}</td>
                    </tr>
                    <tr>
                        <th>Věk</th>
                        <td>{{ NPC.vek }}</td>
                    </tr>
                    <tr>
                        <th>Výška</th>
                        <td>{{ NPC.vyska }}</td>
                    </tr>
                    {% if NPC.oci %}
                    <tr>
                        <th>Oči</th>
                        <td>{{ NPC.oci }}</td>
                    </tr>
                    {% endif %}
                    {% if NPC.oblicej %}
                    <tr>
                        <th>Obličej</th>
                        <td>{{ NPC.oblicej }}</td>
                    </tr>
                    {% endif %}
                    {% if NPC.kladne_vlastnosti %}
                    <tr>
                        <th>Kladné vlastnosti</th>
                        <td>{{ NPC.kladne_vlastnosti }}</td>
                    </tr>
                    {% endif %}
                    {% if NPC.zaporne_vlastnosti %}
                    <tr>
                        <th>Záporné vlastnosti</th>
                        <td>{{ NPC.zaporne_vlastnosti }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <th>Specifické znaky</th>
                        <td>{{ NPC.specifickeZnaky }}</td>
                    </tr>
                    <tr>
                        <th>Vztah k hráčům</th>
                        <td>{{ NPC.get_vztahHraci_display }}</td>
                    </tr>
                    <tr>
                        <th>Stát</th>
                        <td>{{ NPC.stat_nazev }}</td>
                    </tr>
                    <tr>
                        <th>Povaha</th>
                        <td>{{ NPC.povaha }}</td>
                    </tr>
                    <tr>
                        <th>Město</th>
                        <td>
                            <ul>
                                {% for m in NPC.mesto.all %}
                                    <li>{{ m }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                    {% for s in spravci %}
                        {% if s.spravce_id == NPC.idnpc %}
                        <tr>
                            <th>Správce města</th>
                            <td>
                                {{ s.mesto.nazev }} ({{ s.mesto.stat_nazev.nazev }})
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    {% for v in vladce %}
                        {% if v.vladce_id == NPC.idnpc %}
                        <tr>
                            <th>Vládce státu</th>
                            <td>
                                <b>{{ v.stat.nazev }} ({{ v.stat.politicke_usporadani }})</b>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-7">
            <h2>StatTable</h2>
            <table class="npc-table">
                <thead>
                    <tr>
                        <th>Síla</th>
                        <th>Obratnost</th>
                        <th>Výdrž</th>
                        <th>Inteligence</th>
                        <th>Moudrost</th>
                        <th>Charisma</th>
                    </tr>
                </thead>
                <tbody>
                    {% for stattable in stattable %}
                        <tr>
                            <td>{{ stattable.sila }}&nbsp;[{{ stattable.sila_modifier }}]</td>
                            <td>{{ stattable.obratnost }}&nbsp;[{{ stattable.obratnost_modifier}}]</td>
                            <td>{{ stattable.vydrz }}&nbsp;[{{ stattable.vydrz_modifier }}]</td>
                            <td>{{ stattable.inteligence }}&nbsp;[{{ stattable.inteligence_modifier }}]</td>
                            <td>{{ stattable.moudrost }}&nbsp;[{{ stattable.moudrost_modifier }}]</td>
                            <td>{{ stattable.charisma }}&nbsp;[{{ stattable.charisma_modifier }}]</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="6">No StatTable available.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
                <h2>Basic stats table</h2>
                <table class="npc-table">
                    <thead>
                        <tr>
                            <th>Brnění</th>
                            <th>Životy</th>
                            <th>Kostky životů</th>
                            <th>Rychlost</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for stattable in stattable %}
                            <tr>
                                <td>{{ stattable.ac }}</td>
                                <td>{{ stattable.health_die }}</td>
                                <td>{{ stattable.roll_health }}</td>
                                <td>{{ stattable.speed }} sáhů</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="6">No StatTable available.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            <h2>Actions</h2>
            <table class="npc-table">
                <thead>
                    <tr>
                        <th>Název</th>
                        <th>Maximální poškození</th>
                        <th>Bonus k zásahu</th>
                        <th>Dosah</th>
                        <th>Dosah na dálku</th>
                        <th>DC</th>
                        <th>Popis</th>
                    </tr>
                </thead>
                <tbody>
                    {% for action in actions %}
                        <tr>
                            <td>{{ action.nazev }}</td>
                            <td>{{ action.max_dmg }}</td>
                            <td>{{ action.bonus_to_hit }}</td>
                            <td>{{ action.reach }}</td>
                            <td>{{ action.range }}</td>
                            <td>{{ action.dc }}</td>
                            <td>{{ action.desc }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="8">No Actions available.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>